# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts-as-taggable-on-padrino}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Bleigh", "John Knott"]
  s.date = %q{2011-06-30}
  s.description = %q{Padrino version of the popular Rails tagging plugin. With ActsAsTaggableOnPadrino, you could tag a single model on several contexts, such as skills, interests, and awards. It also provides other advanced functionality.}
  s.email = %q{john.knott@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    "CHANGELOG",
    "Gemfile",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "acts-as-taggable-on-padrino.gemspec",
    "lib/acts-as-taggable-on-padrino.rb",
    "lib/acts_as_taggable_on_padrino/tag.rb",
    "lib/acts_as_taggable_on_padrino/taggable.rb",
    "lib/acts_as_taggable_on_padrino/taggable/cache.rb",
    "lib/acts_as_taggable_on_padrino/taggable/collection.rb",
    "lib/acts_as_taggable_on_padrino/taggable/core.rb",
    "lib/acts_as_taggable_on_padrino/taggable/ownership.rb",
    "lib/acts_as_taggable_on_padrino/taggable/related.rb",
    "lib/acts_as_taggable_on_padrino/taggable/tag_list.rb",
    "lib/acts_as_taggable_on_padrino/tagger.rb",
    "lib/acts_as_taggable_on_padrino/tagging.rb",
    "lib/acts_as_taggable_on_padrino/tags_helper.rb",
    "lib/tasks/generate_migration.rb",
    "lib/tasks/templates/migration.rb",
    "spec/acts_as_taggable_on_padrino/acts_as_taggable_on_spec.rb",
    "spec/acts_as_taggable_on_padrino/acts_as_tagger_spec.rb",
    "spec/acts_as_taggable_on_padrino/tag_list_spec.rb",
    "spec/acts_as_taggable_on_padrino/tag_spec.rb",
    "spec/acts_as_taggable_on_padrino/taggable_spec.rb",
    "spec/acts_as_taggable_on_padrino/tagger_spec.rb",
    "spec/acts_as_taggable_on_padrino/tagging_spec.rb",
    "spec/acts_as_taggable_on_padrino/tags_helper_spec.rb",
    "spec/bm.rb",
    "spec/models.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/johnknott/acts-as-taggable-on-padrino}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{ActsAsTaggableOnPadrino is a tagging plugin for Padrino that provides multiple tagging contexts on a single model.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0.0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<mysql>, [">= 0"])
      s.add_development_dependency(%q<pg>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 3.0.0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<mysql>, [">= 0"])
      s.add_dependency(%q<pg>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 3.0.0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<mysql>, [">= 0"])
    s.add_dependency(%q<pg>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
  end
end

